language: rust
rust: stable
env: RUST_BACKTRACE=full
os:
- linux
- osx
- windows
script:
- "cargo test"
- "cargo test --features num-traits"
- "cargo test --features serde"
- "cargo test --features num-traits --features serde"
